apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    replicas: 2
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.6.4
      pullPolicy: IfNotPresent
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
